# Generated by Django 5.1.1 on 2024-10-21 20:26

import django.db.models.deletion
import iter8.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iter8', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='reviewee',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviewee_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='reviewer',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviewer_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment_attachment',
            name='attachment',
            field=models.FileField(upload_to=iter8.models.Assignment_attachment.assignment_directory_path),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iter8.subtask'),
        ),
    ]
