# Generated by Django 5.1.1 on 2024-10-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iter8', '0003_alter_assignment_reviewee_alter_assignment_reviewer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteration',
            old_name='remarks',
            new_name='remark',
        ),
    ]
