# Generated by Django 5.1.1 on 2024-10-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iter8', '0004_rename_remarks_iteration_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteration',
            name='subtask',
        ),
        migrations.AddField(
            model_name='iteration',
            name='reviewee_subtask',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iter8.reviewee_subtask'),
        ),
    ]
